version: '3.7'

services:

    php:
        build:
            context: './.docker/php'
            dockerfile: 'Dockerfile'
            args:
                uid: '1000'
                login: 'dev'
        user: '1000'
        volumes:
            - './:/app'
        working_dir: '/app'
        tty: 'true'
        stdin_open: 'true'
